// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoList_API.Data;

#nullable disable

namespace TodoList_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240423121430_SeCreaDatos")]
    partial class SeCreaDatos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TodoList_API.Models.Tarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEliminacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioCreador")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tareas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Detalle = "hola",
                            FechaActualizacion = new DateTime(2024, 4, 23, 9, 14, 30, 403, DateTimeKind.Local).AddTicks(4903),
                            FechaCreacion = new DateTime(2024, 4, 23, 9, 14, 30, 403, DateTimeKind.Local).AddTicks(4889),
                            FechaEliminacion = new DateTime(2024, 4, 23, 9, 14, 30, 403, DateTimeKind.Local).AddTicks(4904),
                            Titulo = "Sacar a pasear perros",
                            UsuarioCreador = 1
                        },
                        new
                        {
                            Id = 2,
                            Detalle = "hola",
                            FechaActualizacion = new DateTime(2024, 4, 23, 9, 14, 30, 403, DateTimeKind.Local).AddTicks(4907),
                            FechaCreacion = new DateTime(2024, 4, 23, 9, 14, 30, 403, DateTimeKind.Local).AddTicks(4906),
                            FechaEliminacion = new DateTime(2024, 4, 23, 9, 14, 30, 403, DateTimeKind.Local).AddTicks(4908),
                            Titulo = "Ir a hacer las compras",
                            UsuarioCreador = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
